CREATE DATABASE IF NOT EXISTS salve;

USE salve;

CREATE TABLE IF NOT EXISTS login (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(20) NOT NULL,
password VARCHAR(256) NOT NULL,
type ENUM("WORKER", "CUSTOMER")
);

CREATE TABLE IF NOT EXISTS item (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(256),
description VARCHAR(256),
price FLOAT(32),
stock INTEGER,
image VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS worker (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(20),
ssn VARCHAR(11),
login_id INTEGER,
FOREIGN KEY (login_id) REFERENCES login(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS customer (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(20),
login_id INTEGER,
FOREIGN KEY (login_id) REFERENCES login(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS history_customers (
customer_id INTEGER,
order_id INTEGER PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS history_items (
item_id INTEGER,
order_id INTEGER,
quantity INTEGER,
FOREIGN KEY (order_id) REFERENCES history_customers(order_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS contact (
name VARCHAR(30),
email VARCHAR(30),
message MEDIUMTEXT
);